// CrossCheck API types for Vouched integration

export interface CrossCheckVerificationRequest {
  firstName: string;
  lastName: string;
  phone: string;
  email?: string;
  ipAddress?: string;
  dateOfBirth?: string;
  address?: {
    streetAddress?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
}

export interface CrossCheckPhoneResult {
  errors: string[];
  warnings: string[];
  isMatch: boolean;
  isValid: boolean;
  name: string | null;
  ageRange: string | null;
  carrier: string | null;
  isPrepaid: boolean | null;
  isCommercial: boolean | null;
  isDisposable: boolean | null;
  type: string | null;
  lastSeenDays: number | null;
}

export interface CrossCheckEmailResult {
  errors: string[];
  warnings: string[];
  isMatch: boolean;
  isValid: boolean;
  name: string | null;
  ageRange: string | null;
  isAutoGenerated: boolean | null;
  isDisposable: boolean | null;
  daysFirstSeen: number | null;
  emailDomainCreationDate: string | null;
}

export interface CrossCheckVerificationResponse {
  id: string;
  result: {
    success?: boolean;
    address: unknown | null;
    email: CrossCheckEmailResult | null;
    phone: CrossCheckPhoneResult | null;
    ageRange: string | null;
    gender: Record<string, number | null> | null;
    confidences: {
      identity: number | null;
      activity: number | null;
      darkweb: number | null;
    };
    ip: {
      isValid: boolean;
      distance: number | null;
    } | null;
    identityAnalysisScoreVersion: string | null;
    ipAddress: Record<string, unknown> | null;
  };
  request: {
    firstName: string;
    lastName: string;
    phone: string;
    email?: string;
    ipAddress?: string;
    store?: boolean;
  };
}

export interface CrossCheckVerificationError {
  error: string;
  message: string;
  code: string;
  details?: string;
}

export type CrossCheckApiResponse = CrossCheckVerificationResponse | CrossCheckVerificationError;

// Type guards
export function isCrossCheckVerificationResponse(response: CrossCheckApiResponse): response is CrossCheckVerificationResponse {
  return 'id' in response && 'result' in response;
}

export function isCrossCheckVerificationError(response: CrossCheckApiResponse): response is CrossCheckVerificationError {
  return 'error' in response && 'message' in response && 'code' in response;
}
